spring:
  application:
    name: monge-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://grand-osprey-71.clerk.accounts.dev
          jwk-set-uri: https://grand-osprey-71.clerk.accounts.dev/.well-known/jwks.json
